import { TDatabase } from './TDatabase';
import { TEntityTableDefinitions } from './TEntityTableDefinitions';

export const entityTableDefinitions: TEntityTableDefinitions<TDatabase> = {
	users: {
		id: { type: 'text', isPrimaryKey: true, isNotNull: true },
		displayName: { type: 'text', isPrimaryKey: false, isNotNull: true },
		email: { type: 'text', isPrimaryKey: false, isNotNull: true },
		createdAt: { type: 'double precision', isPrimaryKey: false, isNotNull: true },
		ipAddress: { type: 'text', isPrimaryKey: false, isNotNull: true },
	},
	groups: {
		id: { type: 'text', isPrimaryKey: true, isNotNull: true },
		name: { type: 'text', isPrimaryKey: false, isNotNull: true },
		createdAt: { type: 'double precision', isPrimaryKey: false, isNotNull: true },
		updatedAt: { type: 'double precision', isPrimaryKey: false, isNotNull: true },
		invitationToken: { type: 'text', isPrimaryKey: false, isNotNull: true },
	},
	pages: {
		id: { type: 'text', isPrimaryKey: true, isNotNull: true },
		name: { type: 'text', isPrimaryKey: false, isNotNull: true },
		createdAt: { type: 'double precision', isPrimaryKey: false, isNotNull: true },
		updatedAt: { type: 'double precision', isPrimaryKey: false, isNotNull: true },
		type: { type: 'text', isPrimaryKey: false, isNotNull: true },
		body: { type: 'text', isPrimaryKey: false, isNotNull: true },
		startsAt: { type: 'text', isPrimaryKey: false, isNotNull: false },
		endsAt: { type: 'text', isPrimaryKey: false, isNotNull: false },
	},
	properties: {
		id: { type: 'text', isPrimaryKey: true, isNotNull: true },
		key: { type: 'text', isPrimaryKey: false, isNotNull: true },
		type: { type: 'text', isPrimaryKey: false, isNotNull: true },
		value: { type: 'text', isPrimaryKey: false, isNotNull: false },
	},
	usertagregistrations: {
		id: { type: 'text', isPrimaryKey: true, isNotNull: true },
		user: { type: 'text', isPrimaryKey: false, isNotNull: true, references: 'users' },
		tag: { type: 'text', isPrimaryKey: false, isNotNull: true, references: 'usertags' },
		expiresAt: { type: 'text', isPrimaryKey: false, isNotNull: false },
	},
	usertags: {
		id: { type: 'text', isPrimaryKey: true, isNotNull: true },
		name: { type: 'text', isPrimaryKey: false, isNotNull: true },
		displayName: { type: 'text', isPrimaryKey: false, isNotNull: true },
	},
	grouptags: {
		id: { type: 'text', isPrimaryKey: true, isNotNull: true },
		name: { type: 'text', isPrimaryKey: false, isNotNull: true },
		displayName: { type: 'text', isPrimaryKey: false, isNotNull: true },
	},
	pagetags: {
		id: { type: 'text', isPrimaryKey: true, isNotNull: true },
		name: { type: 'text', isPrimaryKey: false, isNotNull: true },
		displayName: { type: 'text', isPrimaryKey: false, isNotNull: true },
	},
	usertaggrantabilities: {
		id: { type: 'text', isPrimaryKey: true, isNotNull: true },
		tag: { type: 'text', isPrimaryKey: false, isNotNull: true },
		expires: { type: 'text', isPrimaryKey: false, isNotNull: false },
		expiresAt: { type: 'text', isPrimaryKey: false, isNotNull: false },
		grantableByUserTag: { type: 'text', isPrimaryKey: false, isNotNull: false, references: 'usertags' },
		grantableByEmailRegex: { type: 'text', isPrimaryKey: false, isNotNull: false },
	},
	apitokens: {
		id: { type: 'text', isPrimaryKey: true, isNotNull: true },
		token: { type: 'text', isPrimaryKey: false, isNotNull: true },
		createdAt: { type: 'double precision', isPrimaryKey: false, isNotNull: true },
		permission: { type: 'text[]', isPrimaryKey: false, isNotNull: true },
		user: { type: 'text', isPrimaryKey: false, isNotNull: true, references: 'users' },
	},
	subjects: {
		id: { type: 'text', isPrimaryKey: true, isNotNull: true },
		code: { type: 'text', isPrimaryKey: false, isNotNull: false },
		name: { type: 'text', isPrimaryKey: false, isNotNull: true },
		updatedAt: { type: 'double precision', isPrimaryKey: false, isNotNull: true },
		nameRuby: { type: 'text', isPrimaryKey: false, isNotNull: false },
		classes: { type: 'text[]', isPrimaryKey: false, isNotNull: true },
		grades: { type: 'double precision[]', isPrimaryKey: false, isNotNull: true },
		units: { type: 'text', isPrimaryKey: false, isNotNull: false },
	},
	categories: {
		id: { type: 'text', isPrimaryKey: true, isNotNull: true },
		name: { type: 'text', isPrimaryKey: false, isNotNull: true },
		displayName: { type: 'text', isPrimaryKey: false, isNotNull: true },
		description: { type: 'text', isPrimaryKey: false, isNotNull: true },
		requiredUnits: { type: 'text', isPrimaryKey: false, isNotNull: false },
		studentIDRegex: { type: 'text[]', isPrimaryKey: false, isNotNull: true },
	},
	subjectsemesters: {
		id: { type: 'text', isPrimaryKey: true, isNotNull: true },
		name: { type: 'text', isPrimaryKey: false, isNotNull: true },
		displayName: { type: 'text', isPrimaryKey: false, isNotNull: true },
		startsAt: { type: 'double precision', isPrimaryKey: false, isNotNull: true },
		endsAt: { type: 'double precision', isPrimaryKey: false, isNotNull: true },
	},
	subjectweeks: {
		id: { type: 'text', isPrimaryKey: true, isNotNull: true },
		name: { type: 'text', isPrimaryKey: false, isNotNull: true },
		displayName: { type: 'text', isPrimaryKey: false, isNotNull: true },
		posOnTimetable: { type: 'text', isPrimaryKey: false, isNotNull: true },
		startsAt: { type: 'double precision', isPrimaryKey: false, isNotNull: true },
		endsAt: { type: 'double precision', isPrimaryKey: false, isNotNull: true },
	},
	teachers: {
		id: { type: 'text', isPrimaryKey: true, isNotNull: true },
		name: { type: 'text', isPrimaryKey: false, isNotNull: true },
		nameRuby: { type: 'text', isPrimaryKey: false, isNotNull: true },
	},
	places: {
		id: { type: 'text', isPrimaryKey: true, isNotNull: true },
		name: { type: 'text', isPrimaryKey: false, isNotNull: true },
		numbering: { type: 'text', isPrimaryKey: false, isNotNull: true },
	},
	sessions: {
		id: { type: 'text', isPrimaryKey: true, isNotNull: true },
		name: { type: 'text', isPrimaryKey: false, isNotNull: true },
		user: { type: 'text', isPrimaryKey: false, isNotNull: true, references: 'users' },
		ipAddress: { type: 'text', isPrimaryKey: false, isNotNull: true },
		loggedInAt: { type: 'double precision', isPrimaryKey: false, isNotNull: true },
		expiresAt: { type: 'double precision', isPrimaryKey: false, isNotNull: true },
	},
	createsessionrequests: {
		id: { type: 'text', isPrimaryKey: true, isNotNull: true },
		createdAt: { type: 'double precision', isPrimaryKey: false, isNotNull: true },
		user: { type: 'text', isPrimaryKey: false, isNotNull: true, references: 'users' },
		isDisposed: { type: 'boolean', isPrimaryKey: false, isNotNull: true },
		token: { type: 'text', isPrimaryKey: false, isNotNull: true },
	},
	usertagrequests: {
		id: { type: 'text', isPrimaryKey: true, isNotNull: true },
		email: { type: 'text', isPrimaryKey: false, isNotNull: true },
		user: { type: 'text', isPrimaryKey: false, isNotNull: true, references: 'users' },
		createdAt: { type: 'double precision', isPrimaryKey: false, isNotNull: true },
		tag: { type: 'text', isPrimaryKey: false, isNotNull: true, references: 'usertags' },
		grantability: { type: 'text', isPrimaryKey: false, isNotNull: true, references: 'usertaggrantabilities' },
		token: { type: 'text', isPrimaryKey: false, isNotNull: true },
		isDisposed: { type: 'boolean', isPrimaryKey: false, isNotNull: true },
	},
	undochangeemailrequests: {
		id: { type: 'text', isPrimaryKey: true, isNotNull: true },
		createdAt: { type: 'double precision', isPrimaryKey: false, isNotNull: true },
		email: { type: 'text', isPrimaryKey: false, isNotNull: true },
		user: { type: 'text', isPrimaryKey: false, isNotNull: true, references: 'users' },
	},
};
