@startuml "Class Diagram"

title "Class Diagram"

class User {
  + readonly id: string
  + email: string
  + name: string
  + displayName: string
  + readonly createdAt: number
  + readonly ipRegisteredFrom: string
  + registrationExpiresAt?: number
  + verificationExpiresAt?: number
}

class Group {
  + readonly id: string
  + name: string
  + displayName: string
  + readonly createdAt: number
  + isAdmin: boolean
  + invitationCode: string
}

class Membership {
  type: 'admin' | 'member'
}

class Bookmark {
}

rectangle "Entities about Authentication" {
  class Token {
    + readonly id: string
    + readonly secret: string
    + readonly type: 'cookie' | 'bearer'
    + readonly expiresAt: number
  }

  class RequestFromUser {
    + readonly id: string
    + readonly secret: string
    + readonly expiresAt: number
    + readonly type: 'token' | 'verification'
  }
}

class Permission {
  + readonly id: string
  + type: 'read' | 'write'
  + readonly expiresAt: number
}

rectangle "Entities about Item" {
  class Item {
    + readonly id: string
    + name: string
    + readonly createdAt: number
    + updatedAt: number
    + isPublic: boolean
  }

  class Attribute {
    + parentItemType: Item['type']
    + key: string
    + valueString?: string
    + valueNumber?: number
    + valueBoolean?: boolean
    + showOnSummary: boolean
  }

  diamond AttributeDiamond
}

User "1" *-- "0..*" Token : owner <
User "1" *-- "0..5" RequestFromUser : requestedFrom <
User "1..*" -- "0..*" Group : belongsTo >
Membership . (User, Group)
User "0..*" -- "0..*" Item : likes >
Bookmark . (User, Item)

Group "1" *--* "0..*" Item : grantsTo <
Permission . (Group, Item)
Group "1" *-- "0..*" Item : owner <

Token "0..*" --* "0..1" Permission : has >

Item "0..*" -- "1" Item : type >
Item "1" *-- "0..*" AttributeDiamond : parent <
Item "0..1" -- "0..*" AttributeDiamond : valueItem? <
AttributeDiamond .. Attribute

@enduml
